spring.application.name=csr_blog_v1
//spring.application.active=dev
spring.profiles.active=dev


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method


